name: Deploy Ansible Playbook to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible and Azure dependencies
        run: |
          sudo apt update
          sudo apt install ansible -y
          pip install ansible[azure]

      - name: Authenticate with Azure
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Run Ansible Playbook
        run: |
          ansible-playbook deploy_vm.yml
